########################################################################################################################

# hii welcome to ChatMinigames: a lightweight, open-sourced and customizable plugin for chat minigames
# Source code: https://github.com/UwUAroze/ChatMinigames

# Config.yml:
# After making any changes, make sure to reload with /cmg reload
# To reset the config, delete this file, then restart your server or /cmg reload.
# Default config: https://github.com/UwUAroze/ChatMinigames/tree/master/src/main/resources/config.yml

# Formatting:
# Hex (&#<hex code>) and regular colour codes (&<code>) are supported:
# Example: "Woah &cRed&r!!!"
# Hex example: "Woah, a &#ff6e6eFancier Red&r!!"

# Placeholders:
# Some configurable messages support placeholders, for instance the numbers in the math game; these will be clarified
# in comments surrounding the corresponding config options.

########################################################################################################################

# Comma separated list of words to be randomised and used in applicable minigames; namely Rush and Unscramble
# Spaces will be ignored.

wordList:
  "Avocado, Blizzard, Blossom, Blueberry, Brilliant, Butterfly, Cactus, Canyon, Cheetah, Cinnamon,
  Coconut, Compass, Crimson, Crystal, Dolphin, Dragon, Enormous, Feather, Flamingo, Forest,
  Frozen, Galaxy, Giraffe, Glacier, Granite, Hamster, Horizon, Hurricane, Jungle, Kingdom,
  Lantern, Lobster, Meadow, Mountain, Muffin, Mustard, Octopus, Panther, Pebble, Penguin,
  Phantom, Pineapple, Pretzel, Pumpkin, Puzzle, Rainbow, Rocket, Salmon, Sapphire, Skeleton,
  Spaghetti, Spectrum, Starfish, Thunder, Tornado, Treasure, Umbrella, Vibrant, Volcano, Walrus,
  Whisper, Wildfire, Wizard, Wombat"

########################################################################################################################

# List of commands to be executed when a player wins minigames, presumably to reward them.
rewards:
  math:
    - "c eco add {player} money 100 Chat Game Win"

  rush:
    - "c eco add {player} money 100 Chat Game Win"

  unscramble:
    - "c eco add {player} money 100 Chat Game Win"

########################################################################################################################

effects:
  sound: # Should a sound effect play to a winning player? (You can test these with /playsound)
    enabled: true
    sound: "block.note_block.pling"
    volume: 1 # 0-1
    pitch: 2 # 0-2

########################################################################################################################

extra-game-settings: # Extra settings unique to individual games
  math:
    arithmetic: # Settings for arithmetic questions
      multiplication:
        symbol: "x"
        min-value: 2
        max-value: 12

      division: # Only numbers between these values that divide to make a whole number will be chosen.
        symbol: "รท"
        min-value: 2
        max-value: 100

      addition:
        symbol: "+"
        min-value: 5
        max-value: 50

      subtraction:
        symbol: "-"
        min-value: 5
        max-value: 50
        allow-negative-answers: false # Should equations with negative answers be allowed? (e.g. 26 - 30 = -4)

########################################################################################################################

minigame-messages: # All messages relating to minigames - start/end broadcasts, private messages, etc.
  starting-hover: # Text to be shown up on hovering over the game start message
    reactionTime: "&#ffd4e3&oPsst.. click me!"

  game-start: # Messages to broadcast when a specific game starts
    math: # Available placeholders: {num1}, {num2}, {operation}
      - "&7&m                            "
      - "&#ffb3a6&lMinigame! &#734841| &#ffb3a6Math"
      - ""
      - "&#ffb3a6Correctly answer this the fastest to gain &#ff8787100 money!"
      - "&#ffb3a6Equation: &#ff8787{num1}{operation}{num2}"
      - "&7&m                            "

    rush: # Available placeholders: {answer}
      - "&7&m                            "
      - "&#ffb3a6&lMinigame! &#734841| &#ffb3a6Rush"
      - ""
      - "&#ffb3a6Type the word the fastest for &#ff8787100 money!"
      - "&#ffb3a6Word: &#ff8787{answer}"
      - "&7&m                            "

    unscramble: # Available placeholders: {scrambled}
      - "&7&m                            "
      - "&#ffb3a6&lMinigame! &#734841| &#ffb3a6Unscramble"
      - ""
      - "&#ffb3a6Unscramble the word the fastest for &#ff8787100 money!"
      - "&#ffb3a6Word: &#ff8787{scrambled}"
      - "&7&m                            "

    reactionTime: # No available placeholders.
    # PS: Extra space increases the clickable area for this minigame.
      - "&7&m                            "
      - "&#ffb3a6&lMinigame! &#734841| &#ffb3a6Reaction Time"
      - "                                                                  "
      - "&#ffb3a6Click this message the fastest for &#ff8787100 money!"
      - "&7&m                            "


  answered-correctly-broadcast: # Messages to broadcast for when a player completes a specific game
    math: # Available placeholders: {num1}, {num2}, {operation}, {answer}, {elapsedTime}, {player}
      - "&7&m                            "
      - "&#ffb3a6&lMinigame! &#734841| &#ffb3a6Math"
      - "&#ffb3a6{player} correctly answered the equation in &#ff8787{elapsedTime}"
      - "&#ffb3a6Equation: &#ff8787{num1}{operation}{num2} = {answer}"
      - "&7&m                            "

    rush: # Available placeholders: {answer}, {elapsedTime}, {player}
      - "&7&m                            "
      - "&#ffb3a6&lMinigame! &#734841| &#ffb3a6Rush"
      - "&#ffb3a6{player} correctly typed the word in &#ff8787{elapsedTime}"
      - "&#ffb3a6Word: &#ff8787{answer}"
      - "&7&m                            "

    unscramble: # Available placeholders: {scrambled}, {answer}, {elapsedTime}, {player}
      - "&7&m                            "
      - "&#ffb3a6&lMinigame! &#734841| &#ffb3a6Unscramble"
      - "&#ffb3a6{player} correctly answered in &#ff8787{elapsedTime}"
      - "&#ffb3a6The word was: &#ff8787{answer}"
      - "&7&m                            "

    reactionTime: # Available placeholders: {elapsedTime}, {player}
      - "&7&m                            "
      - "&#ffb3a6&lMinigame! &#734841| &#ffb3a6Reaction Time"
      - ""
      - "&#ffb3a6{player} clicked the message in &#ff8787{elapsedTime}"
      - "&7&m                            "


  answered-correctly-private: # Private message to be sent to a player who completes a specific game
    math:
      - "&7&oCorrectly solved math problem, &#ffb3a6&o+100 Money"

    rush:
      - "&7&oCorrectly typed word, &#ffb3a6&o+100 Money"

    unscramble:
      - "&7&oCorrectly unscrambled word, &#ffb3a6&o+100 Money"

    reactionTime:
      - "&7&oFirst to click, &#ffb3a6&o+100 Money"

########################################################################################################################

auto-start:
  enabled: true
  min-interval: 180 # seconds (minimum delay before the next game starts)
  max-interval: 600 # seconds (maximum delay before the next game starts)
  games: # Toggle individual games on/off
    math: true
    rush: true
    unscramble: true

########################################################################################################################

misc-settings:
  case-sensitive: false # Should answer checking for applicable games (unscramble/rush) be case-sensitive?
  cancel-winning-answers: true # Should the player's message be cancelled (not be sent) if it was a correct answer?
  ignore-cancelled-messages: true # Should cancelled messages (eg: muted players) be ignored?

########################################################################################################################